"""add_case_number_to_cases

Revision ID: 4f90354d3b04
Revises: 
Create Date: 2026-06-19 18:18:04.028789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f90354d3b04'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cases', 'victim_email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('cases_case_number_key'), 'cases', type_='unique')
    op.create_index(op.f('ix_cases_case_number'), 'cases', ['case_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cases_case_number'), table_name='cases')
    op.create_unique_constraint(op.f('cases_case_number_key'), 'cases', ['case_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('cases', 'victim_email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
